version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - errcheck
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gomodguard
    - goprintffuncname
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
#    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    lll:
      line-length: 180
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - scopelint
        path: errors/error_handler_test.go
      - linters:
          - scopelint
        path: config/config_test.go
      - linters:
          - staticcheck
        path: codegen
        text: 'ST1003:'
      - linters:
          - golint
        path: codegen
        text: .*should be.*
      - linters:
          - funlen
          - govet
          - mnd
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
