service:
  golangci-lint-version: 1.29.0

linters-settings:
  lll:
    line-length: 180

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - goimports
    - golint
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - maligned
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace

  # disable: # as at 1.27.0
  #   - dupl
  #   - gochecknoglobals
  #   - goerr113
  #   - gomnd
  #   - gosec
  #   - lll
  #   - nestif
  #   - stylecheck
  #   - testpackage
  #   - wsl
  #   - unused

issues:
  exclude-rules:
    #Ignore variable scope linting
    - path: "errors/error_handler_test.go"
      linters:
        - scopelint
    - path: "config/config_test.go"
      linters:
        - scopelint
    # Ignore things like "FormId should be FormID"
    - path: codegen
      text: "ST1003:"
      linters:
        - stylecheck
    # Ignore things like "FormId should be FormID"
    - path: codegen
      text: ".*should be.*"
      linters:
        - golint
    
    - path: _test\.go
      linters:
        - govet # Ignore err shadowing in test files
        - gomnd 
        - funlen # Ignore function length for tests

run:
  deadline: 2m

