#!/bin/bash
# Usage: ./test-arrai [out]

set -x

out="${1+/$1}"

go_gen=codegen/tests$out
arrai_gen=codegen/arrai/tests$out

target=arrai
if [ -n "$out" ]; then
    target=$arrai_gen
fi

make $target && colordiff -rwuB $go_gen/ $arrai_gen/ | less -FRX
