// Code generated by sysl DO NOT EDIT.
package simplesg

import (
	"context"

	"github.com/anz-bank/sysl-go/codegen/tests/simple"
	pb "github.com/anz-bank/sysl-go/codegen/tests/simplegrpc/simplepb"
)

// GetStuff Client
type GetStuffClient struct {
	PostStuff func(ctx context.Context, req *simple.PostStuffRequest) (*simple.Str, error)
}

// GrpcServiceInterface for SimpleGrpc
type GrpcServiceInterface struct {
	GetStuff func(ctx context.Context, req *pb.GetStuffRequest, client GetStuffClient) (*pb.GetStuffResponse, error)
}
