// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: simplegrpc.proto

package simplepb

import (
	context "context"
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetStuffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InnerStuff     string `protobuf:"bytes,1,opt,name=innerStuff,proto3" json:"innerStuff,omitempty"`
	SensitiveStuff string `protobuf:"bytes,2,opt,name=sensitiveStuff,proto3" json:"sensitiveStuff,omitempty"`
	TimeStuff      string `protobuf:"bytes,3,opt,name=timeStuff,proto3" json:"timeStuff,omitempty"`
}

func (x *GetStuffRequest) Reset() {
	*x = GetStuffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simplegrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStuffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStuffRequest) ProtoMessage() {}

func (x *GetStuffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simplegrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStuffRequest.ProtoReflect.Descriptor instead.
func (*GetStuffRequest) Descriptor() ([]byte, []int) {
	return file_simplegrpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetStuffRequest) GetInnerStuff() string {
	if x != nil {
		return x.InnerStuff
	}
	return ""
}

func (x *GetStuffRequest) GetSensitiveStuff() string {
	if x != nil {
		return x.SensitiveStuff
	}
	return ""
}

func (x *GetStuffRequest) GetTimeStuff() string {
	if x != nil {
		return x.TimeStuff
	}
	return ""
}

type GetStuffResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Item `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *GetStuffResponse) Reset() {
	*x = GetStuffResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simplegrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStuffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStuffResponse) ProtoMessage() {}

func (x *GetStuffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simplegrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStuffResponse.ProtoReflect.Descriptor instead.
func (*GetStuffResponse) Descriptor() ([]byte, []int) {
	return file_simplegrpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetStuffResponse) GetData() []*Item {
	if x != nil {
		return x.Data
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	A1   string `protobuf:"bytes,2,opt,name=A1,proto3" json:"A1,omitempty"`
	A2   string `protobuf:"bytes,3,opt,name=A2,proto3" json:"A2,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simplegrpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_simplegrpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_simplegrpc_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetA1() string {
	if x != nil {
		return x.A1
	}
	return ""
}

func (x *Item) GetA2() string {
	if x != nil {
		return x.A2
	}
	return ""
}

var File_simplegrpc_proto protoreflect.FileDescriptor

var file_simplegrpc_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x70, 0x62, 0x22, 0x77, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x75, 0x66, 0x66, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x75, 0x66, 0x66, 0x12,
	0x26, 0x0a, 0x0e, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x53, 0x74, 0x75, 0x66,
	0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69,
	0x76, 0x65, 0x53, 0x74, 0x75, 0x66, 0x66, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53,
	0x74, 0x75, 0x66, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x53, 0x74, 0x75, 0x66, 0x66, 0x22, 0x36, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x66,
	0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65,
	0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x3a, 0x0a,
	0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x41, 0x31, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x41, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x41, 0x32, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x41, 0x32, 0x32, 0x4f, 0x0a, 0x0a, 0x53, 0x69, 0x6d,
	0x70, 0x6c, 0x65, 0x47, 0x72, 0x70, 0x63, 0x12, 0x41, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x75, 0x66, 0x66, 0x12, 0x19, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x75, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75,
	0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_simplegrpc_proto_rawDescOnce sync.Once
	file_simplegrpc_proto_rawDescData = file_simplegrpc_proto_rawDesc
)

func file_simplegrpc_proto_rawDescGZIP() []byte {
	file_simplegrpc_proto_rawDescOnce.Do(func() {
		file_simplegrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_simplegrpc_proto_rawDescData)
	})
	return file_simplegrpc_proto_rawDescData
}

var file_simplegrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_simplegrpc_proto_goTypes = []interface{}{
	(*GetStuffRequest)(nil),  // 0: simplepb.GetStuffRequest
	(*GetStuffResponse)(nil), // 1: simplepb.GetStuffResponse
	(*Item)(nil),             // 2: simplepb.Item
}
var file_simplegrpc_proto_depIdxs = []int32{
	2, // 0: simplepb.GetStuffResponse.Data:type_name -> simplepb.Item
	0, // 1: simplepb.SimpleGrpc.GetStuff:input_type -> simplepb.GetStuffRequest
	1, // 2: simplepb.SimpleGrpc.GetStuff:output_type -> simplepb.GetStuffResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_simplegrpc_proto_init() }
func file_simplegrpc_proto_init() {
	if File_simplegrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_simplegrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStuffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simplegrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStuffResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simplegrpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_simplegrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_simplegrpc_proto_goTypes,
		DependencyIndexes: file_simplegrpc_proto_depIdxs,
		MessageInfos:      file_simplegrpc_proto_msgTypes,
	}.Build()
	File_simplegrpc_proto = out.File
	file_simplegrpc_proto_rawDesc = nil
	file_simplegrpc_proto_goTypes = nil
	file_simplegrpc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SimpleGrpcClient is the client API for SimpleGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SimpleGrpcClient interface {
	GetStuff(ctx context.Context, in *GetStuffRequest, opts ...grpc.CallOption) (*GetStuffResponse, error)
}

type simpleGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewSimpleGrpcClient(cc grpc.ClientConnInterface) SimpleGrpcClient {
	return &simpleGrpcClient{cc}
}

func (c *simpleGrpcClient) GetStuff(ctx context.Context, in *GetStuffRequest, opts ...grpc.CallOption) (*GetStuffResponse, error) {
	out := new(GetStuffResponse)
	err := c.cc.Invoke(ctx, "/simplepb.SimpleGrpc/GetStuff", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimpleGrpcServer is the server API for SimpleGrpc service.
type SimpleGrpcServer interface {
	GetStuff(context.Context, *GetStuffRequest) (*GetStuffResponse, error)
}

// UnimplementedSimpleGrpcServer can be embedded to have forward compatible implementations.
type UnimplementedSimpleGrpcServer struct {
}

func (*UnimplementedSimpleGrpcServer) GetStuff(context.Context, *GetStuffRequest) (*GetStuffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStuff not implemented")
}

func RegisterSimpleGrpcServer(s *grpc.Server, srv SimpleGrpcServer) {
	s.RegisterService(&_SimpleGrpc_serviceDesc, srv)
}

func _SimpleGrpc_GetStuff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStuffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleGrpcServer).GetStuff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simplepb.SimpleGrpc/GetStuff",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleGrpcServer).GetStuff(ctx, req.(*GetStuffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SimpleGrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "simplepb.SimpleGrpc",
	HandlerType: (*SimpleGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStuff",
			Handler:    _SimpleGrpc_GetStuff_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "simplegrpc.proto",
}
