// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simplegrpc.proto

package simplepb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetStuffRequest struct {
	InnerStuff           string   `protobuf:"bytes,1,opt,name=innerStuff,proto3" json:"innerStuff,omitempty"`
	SensitiveStuff       string   `protobuf:"bytes,2,opt,name=sensitiveStuff,proto3" json:"sensitiveStuff,omitempty"`
	TimeStuff            string   `protobuf:"bytes,3,opt,name=timeStuff,proto3" json:"timeStuff,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStuffRequest) Reset()         { *m = GetStuffRequest{} }
func (m *GetStuffRequest) String() string { return proto.CompactTextString(m) }
func (*GetStuffRequest) ProtoMessage()    {}
func (*GetStuffRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_111fa7809525fdda, []int{0}
}

func (m *GetStuffRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStuffRequest.Unmarshal(m, b)
}
func (m *GetStuffRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStuffRequest.Marshal(b, m, deterministic)
}
func (m *GetStuffRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStuffRequest.Merge(m, src)
}
func (m *GetStuffRequest) XXX_Size() int {
	return xxx_messageInfo_GetStuffRequest.Size(m)
}
func (m *GetStuffRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStuffRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStuffRequest proto.InternalMessageInfo

func (m *GetStuffRequest) GetInnerStuff() string {
	if m != nil {
		return m.InnerStuff
	}
	return ""
}

func (m *GetStuffRequest) GetSensitiveStuff() string {
	if m != nil {
		return m.SensitiveStuff
	}
	return ""
}

func (m *GetStuffRequest) GetTimeStuff() string {
	if m != nil {
		return m.TimeStuff
	}
	return ""
}

type GetStuffResponse struct {
	Data                 []*Item  `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStuffResponse) Reset()         { *m = GetStuffResponse{} }
func (m *GetStuffResponse) String() string { return proto.CompactTextString(m) }
func (*GetStuffResponse) ProtoMessage()    {}
func (*GetStuffResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_111fa7809525fdda, []int{1}
}

func (m *GetStuffResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStuffResponse.Unmarshal(m, b)
}
func (m *GetStuffResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStuffResponse.Marshal(b, m, deterministic)
}
func (m *GetStuffResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStuffResponse.Merge(m, src)
}
func (m *GetStuffResponse) XXX_Size() int {
	return xxx_messageInfo_GetStuffResponse.Size(m)
}
func (m *GetStuffResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStuffResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStuffResponse proto.InternalMessageInfo

func (m *GetStuffResponse) GetData() []*Item {
	if m != nil {
		return m.Data
	}
	return nil
}

type Item struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	A1                   string   `protobuf:"bytes,2,opt,name=A1,proto3" json:"A1,omitempty"`
	A2                   string   `protobuf:"bytes,3,opt,name=A2,proto3" json:"A2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_111fa7809525fdda, []int{2}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetA1() string {
	if m != nil {
		return m.A1
	}
	return ""
}

func (m *Item) GetA2() string {
	if m != nil {
		return m.A2
	}
	return ""
}

func init() {
	proto.RegisterType((*GetStuffRequest)(nil), "simplepb.GetStuffRequest")
	proto.RegisterType((*GetStuffResponse)(nil), "simplepb.GetStuffResponse")
	proto.RegisterType((*Item)(nil), "simplepb.Item")
}

func init() { proto.RegisterFile("simplegrpc.proto", fileDescriptor_111fa7809525fdda) }

var fileDescriptor_111fa7809525fdda = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0x1a, 0xa4, 0x1d, 0x21, 0x96, 0x39, 0xd5, 0x22, 0x52, 0x72, 0x90, 0x9e, 0x02,
	0x5d, 0xc1, 0x83, 0xb7, 0x05, 0xa1, 0x78, 0x51, 0x48, 0x9f, 0x20, 0x2d, 0x53, 0x59, 0x70, 0x37,
	0xeb, 0xee, 0x54, 0x5f, 0x5f, 0x9c, 0x6c, 0x89, 0x84, 0xde, 0x76, 0xbe, 0xf9, 0xd9, 0xff, 0x63,
	0x60, 0x1e, 0x8d, 0xf5, 0x9f, 0xf4, 0x11, 0xfc, 0xa1, 0xf6, 0xa1, 0xe3, 0x0e, 0xa7, 0x3d, 0xf1,
	0xfb, 0xea, 0x07, 0x6e, 0xb6, 0xc4, 0x3b, 0x3e, 0x1d, 0x8f, 0x0d, 0x7d, 0x9d, 0x28, 0x32, 0xde,
	0x03, 0x18, 0xe7, 0x28, 0x08, 0x5c, 0x64, 0xab, 0x6c, 0x3d, 0x6b, 0xfe, 0x11, 0x7c, 0x80, 0x32,
	0x92, 0x8b, 0x86, 0xcd, 0x37, 0xf5, 0x99, 0x5c, 0x32, 0x23, 0x8a, 0x77, 0x30, 0x63, 0x63, 0x53,
	0x64, 0x22, 0x91, 0x01, 0x54, 0x4f, 0x30, 0x1f, 0x8a, 0xa3, 0xef, 0x5c, 0x24, 0xac, 0xa0, 0x78,
	0x69, 0xb9, 0x5d, 0x64, 0xab, 0xc9, 0xfa, 0x5a, 0x95, 0xf5, 0xd9, 0xb2, 0x7e, 0x65, 0xb2, 0x8d,
	0xec, 0xaa, 0x67, 0x28, 0xfe, 0x26, 0x44, 0x28, 0xde, 0x5a, 0x4b, 0xc9, 0x4f, 0xde, 0x58, 0x42,
	0xae, 0x37, 0xc9, 0x26, 0xd7, 0x1b, 0x99, 0x55, 0xaa, 0xce, 0xb5, 0x52, 0xef, 0x00, 0x3b, 0xf9,
	0x72, 0x1b, 0xfc, 0x01, 0x35, 0x4c, 0xcf, 0x06, 0x78, 0x3b, 0x74, 0x8d, 0xce, 0xb1, 0x5c, 0x5e,
	0x5a, 0xf5, 0xc2, 0xfb, 0x2b, 0x39, 0xe7, 0xe3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf1, 0xc0,
	0x40, 0x30, 0x62, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SimpleGrpcClient is the client API for SimpleGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SimpleGrpcClient interface {
	GetStuff(ctx context.Context, in *GetStuffRequest, opts ...grpc.CallOption) (*GetStuffResponse, error)
}

type simpleGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewSimpleGrpcClient(cc grpc.ClientConnInterface) SimpleGrpcClient {
	return &simpleGrpcClient{cc}
}

func (c *simpleGrpcClient) GetStuff(ctx context.Context, in *GetStuffRequest, opts ...grpc.CallOption) (*GetStuffResponse, error) {
	out := new(GetStuffResponse)
	err := c.cc.Invoke(ctx, "/simplepb.SimpleGrpc/GetStuff", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimpleGrpcServer is the server API for SimpleGrpc service.
type SimpleGrpcServer interface {
	GetStuff(context.Context, *GetStuffRequest) (*GetStuffResponse, error)
}

// UnimplementedSimpleGrpcServer can be embedded to have forward compatible implementations.
type UnimplementedSimpleGrpcServer struct {
}

func (*UnimplementedSimpleGrpcServer) GetStuff(ctx context.Context, req *GetStuffRequest) (*GetStuffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStuff not implemented")
}

func RegisterSimpleGrpcServer(s *grpc.Server, srv SimpleGrpcServer) {
	s.RegisterService(&_SimpleGrpc_serviceDesc, srv)
}

func _SimpleGrpc_GetStuff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStuffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleGrpcServer).GetStuff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simplepb.SimpleGrpc/GetStuff",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleGrpcServer).GetStuff(ctx, req.(*GetStuffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SimpleGrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "simplepb.SimpleGrpc",
	HandlerType: (*SimpleGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStuff",
			Handler:    _SimpleGrpc_GetStuff_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "simplegrpc.proto",
}
