// Code generated by sysl DO NOT EDIT.
package simplegrpc

import (
	"github.com/anz-bank/sysl-go/codegen/tests/simple"
	"github.com/anz-bank/sysl-go/config"
	"github.com/anz-bank/sysl-go/core"
	"github.com/anz-bank/sysl-go/handlerinitialiser"
)

// DownstreamClients for SimpleGrpc
type DownstreamClients struct {
	simpleClient *simple.Client
}

// BuildGrpcHandlerInitialiser ...
func BuildGrpcHandlerInitialiser(serviceInterface GrpcServiceInterface, callback core.GrpcGenCallback, downstream *DownstreamClients) handlerinitialiser.GrpcHandlerInitialiser {
	serviceHandler := NewGrpcServiceHandler(callback, &serviceInterface, downstream.simpleClient)
	return serviceHandler
}

// BuildDownstreamClients ...
func BuildDownstreamClients(cfg *config.DefaultConfig) (*DownstreamClients, error) {
	var err error = nil
	simpleHTTPClient, simpleErr := core.BuildDownstreamHTTPClient("simple", &cfg.GenCode.Downstream.(*DownstreamConfig).Simple)
	if simpleErr != nil {
		return nil, simpleErr
	}

	simpleClient := simple.NewClient(simpleHTTPClient, cfg.GenCode.Downstream.(*DownstreamConfig).Simple.ServiceURL)
	return &DownstreamClients{simpleClient: simpleClient}, err
}

// NewDefaultConfig ...
func NewDefaultConfig() config.DefaultConfig {
	return config.DefaultConfig{
		Library: config.LibraryConfig{},
		GenCode: config.GenCodeConfig{Downstream: &DownstreamConfig{}},
	}

}
