// Code generated by sysl DO NOT EDIT.
package simplegrpc

import (
	"context"

	simplegrpcgrpc "github.com/anz-bank/sysl-go/codegen/tests/simplegrpc/grpc"
)

// GetStuff Client
type GetStuffClient struct {
}

// GrpcServiceInterface for SimpleGrpc
type GrpcServiceInterface struct {
	GetStuff func(ctx context.Context, req *simplegrpcgrpc.GetStuffRequest, client GetStuffClient) (*simplegrpcgrpc.GetStuffResponse, error)
}
