// Code generated by sysl DO NOT EDIT.
package simplegrpc

import (
	"context"
	"time"

	"github.com/anz-bank/sysl-go/codegen/tests/simple"
	pb "github.com/anz-bank/sysl-go/codegen/tests/simplepb"
	"github.com/anz-bank/sysl-go/config"
	"github.com/anz-bank/sysl-go/restlib"
)

// GetStuff Client
type GetStuffClient struct {
	PostStuff func(ctx context.Context, req *simple.PostStuffRequest, opts ...restlib.RestRequestOption) (*simple.Str, error)
}

// GrpcServiceInterface for SimpleGrpc
type GrpcServiceInterface struct {
	GetStuff func(ctx context.Context, req *pb.GetStuffRequest, client GetStuffClient) (*pb.GetStuffResponse, error)
}

// DownstreamConfig for SimpleGrpc
type DownstreamConfig struct {
	ContextTimeout time.Duration               `yaml:"contextTimeout"`
	Simple         config.CommonDownstreamData `yaml:"simple"`
}
