package core

import "go.temporal.io/sdk/worker"

// ensure it implements StoppableServer.
var _ StoppableServer = &TemporalServer{}

type TemporalServer struct {
	Spec TemporalServiceSpec
}

func (t *TemporalServer) Start() error {
	t.Spec.Register()
	return t.Spec.Run(worker.InterruptCh())
}

func (t *TemporalServer) Stop() error {
	// stops worker.
	t.Spec.Stop()
	// closes client.
	t.Spec.Close()
	return nil
}

func (t *TemporalServer) GracefulStop() error {
	return t.Stop()
}

func (t *TemporalServer) GetName() string { return "autogenerated-temporal-server" }
