package core

import "go.temporal.io/sdk/worker"

type TemporalServer[Spec any] struct {
	Spec TemporalServiceSpec[Spec]
}

func (t *TemporalServer[Spec]) Start() error {
	t.Spec.Register()
	return t.Spec.Run(worker.InterruptCh())
}

func (t *TemporalServer[Spec]) Stop() error {
	// stops worker.
	t.Spec.Stop()
	// closes client.
	t.Spec.Close()
	return nil
}

func (t *TemporalServer[Spec]) GracefulStop() error {
	return t.Stop()
}

func (t *TemporalServer[Spec]) GetName() string { return "autogenerated-temporal-server" }

func (t *TemporalServer[Spec]) GetSpec() TemporalServiceSpec[Spec] { return t.Spec }
