// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cards_api.proto

package cardspb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetCardsRequest struct {
	PersonaId            string   `protobuf:"bytes,1,opt,name=persona_id,json=personaId,proto3" json:"persona_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCardsRequest) Reset()         { *m = GetCardsRequest{} }
func (m *GetCardsRequest) String() string { return proto.CompactTextString(m) }
func (*GetCardsRequest) ProtoMessage()    {}
func (*GetCardsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3972b0c891f2b156, []int{0}
}

func (m *GetCardsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCardsRequest.Unmarshal(m, b)
}
func (m *GetCardsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCardsRequest.Marshal(b, m, deterministic)
}
func (m *GetCardsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCardsRequest.Merge(m, src)
}
func (m *GetCardsRequest) XXX_Size() int {
	return xxx_messageInfo_GetCardsRequest.Size(m)
}
func (m *GetCardsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCardsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCardsRequest proto.InternalMessageInfo

func (m *GetCardsRequest) GetPersonaId() string {
	if m != nil {
		return m.PersonaId
	}
	return ""
}

type GetCardsResponse struct {
	Cards                []*Card  `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCardsResponse) Reset()         { *m = GetCardsResponse{} }
func (m *GetCardsResponse) String() string { return proto.CompactTextString(m) }
func (*GetCardsResponse) ProtoMessage()    {}
func (*GetCardsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3972b0c891f2b156, []int{1}
}

func (m *GetCardsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCardsResponse.Unmarshal(m, b)
}
func (m *GetCardsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCardsResponse.Marshal(b, m, deterministic)
}
func (m *GetCardsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCardsResponse.Merge(m, src)
}
func (m *GetCardsResponse) XXX_Size() int {
	return xxx_messageInfo_GetCardsResponse.Size(m)
}
func (m *GetCardsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCardsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCardsResponse proto.InternalMessageInfo

func (m *GetCardsResponse) GetCards() []*Card {
	if m != nil {
		return m.Cards
	}
	return nil
}

func init() {
	proto.RegisterType((*GetCardsRequest)(nil), "cards.v1.GetCardsRequest")
	proto.RegisterType((*GetCardsResponse)(nil), "cards.v1.GetCardsResponse")
}

func init() { proto.RegisterFile("cards_api.proto", fileDescriptor_3972b0c891f2b156) }

var fileDescriptor_3972b0c891f2b156 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x4e, 0x2c, 0x4a,
	0x29, 0x8e, 0x4f, 0x2c, 0xc8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x0b, 0xe8,
	0x95, 0x19, 0x4a, 0x71, 0x43, 0x58, 0x60, 0x61, 0x25, 0x03, 0x2e, 0x7e, 0xf7, 0xd4, 0x12, 0x67,
	0x90, 0x48, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x2c, 0x17, 0x57, 0x41, 0x6a, 0x51,
	0x71, 0x7e, 0x5e, 0x62, 0x7c, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x27, 0x54,
	0xc4, 0x33, 0x45, 0xc9, 0x82, 0x4b, 0x00, 0xa1, 0xa3, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48,
	0x85, 0x8b, 0x15, 0x6c, 0xa8, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x11, 0x9f, 0x1e, 0xcc, 0x32,
	0x3d, 0x90, 0xba, 0x20, 0x88, 0xa4, 0x91, 0x17, 0x17, 0x2b, 0x58, 0x9b, 0x90, 0x23, 0x17, 0x07,
	0xcc, 0x08, 0x21, 0x49, 0x84, 0x5a, 0x34, 0x87, 0x48, 0x49, 0x61, 0x93, 0x82, 0xd8, 0xe8, 0xc4,
	0x19, 0xc5, 0x0e, 0x96, 0x2c, 0x48, 0x4a, 0x62, 0x03, 0xfb, 0xc4, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0xe5, 0xbf, 0xe1, 0x5f, 0xf3, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CardsClient is the client API for Cards service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CardsClient interface {
	GetCards(ctx context.Context, in *GetCardsRequest, opts ...grpc.CallOption) (*GetCardsResponse, error)
}

type cardsClient struct {
	cc *grpc.ClientConn
}

func NewCardsClient(cc *grpc.ClientConn) CardsClient {
	return &cardsClient{cc}
}

func (c *cardsClient) GetCards(ctx context.Context, in *GetCardsRequest, opts ...grpc.CallOption) (*GetCardsResponse, error) {
	out := new(GetCardsResponse)
	err := c.cc.Invoke(ctx, "/cards.v1.Cards/GetCards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardsServer is the server API for Cards service.
type CardsServer interface {
	GetCards(context.Context, *GetCardsRequest) (*GetCardsResponse, error)
}

// UnimplementedCardsServer can be embedded to have forward compatible implementations.
type UnimplementedCardsServer struct {
}

func (*UnimplementedCardsServer) GetCards(ctx context.Context, req *GetCardsRequest) (*GetCardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCards not implemented")
}

func RegisterCardsServer(s *grpc.Server, srv CardsServer) {
	s.RegisterService(&_Cards_serviceDesc, srv)
}

func _Cards_GetCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardsServer).GetCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cards.v1.Cards/GetCards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardsServer).GetCards(ctx, req.(*GetCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cards_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cards.v1.Cards",
	HandlerType: (*CardsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCards",
			Handler:    _Cards_GetCards_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cards_api.proto",
}
