// Code generated by sysl DO NOT EDIT.
package simple

import (
	"context"

	pb "github.com/anz-bank/sysl-go/codegen/tests/simplegrpc/simplepb"
)

// GetStuff Client
type GetStuffClient struct {
}

// GrpcServiceInterface for SimpleGrpc
type GrpcServiceInterface struct {
	GetStuff func(ctx context.Context, req *pb.GetStuffRequest, client GetStuffClient) (*pb.GetStuffResponse, error)
}
