// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: specs.proto

package frontdoor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Resp) Reset() {
	*x = Resp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_specs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp) ProtoMessage() {}

func (x *Resp) ProtoReflect() protoreflect.Message {
	mi := &file_specs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp.ProtoReflect.Descriptor instead.
func (*Resp) Descriptor() ([]byte, []int) {
	return file_specs_proto_rawDescGZIP(), []int{0}
}

func (x *Resp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EncoderId string `protobuf:"bytes,1,opt,name=encoder_id,json=encoderId,proto3" json:"encoder_id,omitempty"`
	Content   string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Req) Reset() {
	*x = Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_specs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req) ProtoMessage() {}

func (x *Req) ProtoReflect() protoreflect.Message {
	mi := &file_specs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req.ProtoReflect.Descriptor instead.
func (*Req) Descriptor() ([]byte, []int) {
	return file_specs_proto_rawDescGZIP(), []int{1}
}

func (x *Req) GetEncoderId() string {
	if x != nil {
		return x.EncoderId
	}
	return ""
}

func (x *Req) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_specs_proto protoreflect.FileDescriptor

var file_specs_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x70, 0x65, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x66,
	0x72, 0x6f, 0x6e, 0x74, 0x64, 0x6f, 0x6f, 0x72, 0x22, 0x20, 0x0a, 0x04, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x3e, 0x0a, 0x03, 0x52, 0x65,
	0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x32, 0x38, 0x0a, 0x09, 0x46, 0x72,
	0x6f, 0x6e, 0x74, 0x64, 0x6f, 0x6f, 0x72, 0x12, 0x2b, 0x0a, 0x08, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x6f, 0x72, 0x12, 0x0e, 0x2e, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x64, 0x6f, 0x6f, 0x72, 0x2e,
	0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x64, 0x6f, 0x6f, 0x72, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x42, 0x22, 0x5a, 0x20, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c,
	0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x3b, 0x66,
	0x72, 0x6f, 0x6e, 0x74, 0x64, 0x6f, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_specs_proto_rawDescOnce sync.Once
	file_specs_proto_rawDescData = file_specs_proto_rawDesc
)

func file_specs_proto_rawDescGZIP() []byte {
	file_specs_proto_rawDescOnce.Do(func() {
		file_specs_proto_rawDescData = protoimpl.X.CompressGZIP(file_specs_proto_rawDescData)
	})
	return file_specs_proto_rawDescData
}

var file_specs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_specs_proto_goTypes = []interface{}{
	(*Resp)(nil), // 0: frontdoor.Resp
	(*Req)(nil),  // 1: frontdoor.Req
}
var file_specs_proto_depIdxs = []int32{
	1, // 0: frontdoor.Frontdoor.Executor:input_type -> frontdoor.Req
	0, // 1: frontdoor.Frontdoor.Executor:output_type -> frontdoor.Resp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_specs_proto_init() }
func file_specs_proto_init() {
	if File_specs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_specs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_specs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_specs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_specs_proto_goTypes,
		DependencyIndexes: file_specs_proto_depIdxs,
		MessageInfos:      file_specs_proto_msgTypes,
	}.Build()
	File_specs_proto = out.File
	file_specs_proto_rawDesc = nil
	file_specs_proto_goTypes = nil
	file_specs_proto_depIdxs = nil
}
