// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: specs.proto

package frontdoor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FrontdoorClient is the client API for Frontdoor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FrontdoorClient interface {
	Executor(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
}

type frontdoorClient struct {
	cc grpc.ClientConnInterface
}

func NewFrontdoorClient(cc grpc.ClientConnInterface) FrontdoorClient {
	return &frontdoorClient{cc}
}

func (c *frontdoorClient) Executor(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/frontdoor.Frontdoor/Executor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FrontdoorServer is the server API for Frontdoor service.
// All implementations must embed UnimplementedFrontdoorServer
// for forward compatibility
type FrontdoorServer interface {
	Executor(context.Context, *Req) (*Resp, error)
	mustEmbedUnimplementedFrontdoorServer()
}

// UnimplementedFrontdoorServer must be embedded to have forward compatible implementations.
type UnimplementedFrontdoorServer struct {
}

func (UnimplementedFrontdoorServer) Executor(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Executor not implemented")
}
func (UnimplementedFrontdoorServer) mustEmbedUnimplementedFrontdoorServer() {}

// UnsafeFrontdoorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FrontdoorServer will
// result in compilation errors.
type UnsafeFrontdoorServer interface {
	mustEmbedUnimplementedFrontdoorServer()
}

func RegisterFrontdoorServer(s grpc.ServiceRegistrar, srv FrontdoorServer) {
	s.RegisterService(&Frontdoor_ServiceDesc, srv)
}

func _Frontdoor_Executor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontdoorServer).Executor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frontdoor.Frontdoor/Executor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontdoorServer).Executor(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

// Frontdoor_ServiceDesc is the grpc.ServiceDesc for Frontdoor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Frontdoor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "frontdoor.Frontdoor",
	HandlerType: (*FrontdoorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Executor",
			Handler:    _Frontdoor_Executor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "specs.proto",
}
