// Code generated by sysl DO NOT EDIT.
package cards

import (
	"context"
	"time"

	pb "github.com/anz-bank/sysl-go/codegen/tests/cardspb"
)

// GetCards Client
type GetCardsClient struct {
}

// GrpcServiceInterface for Cards
type GrpcServiceInterface struct {
	GetCards func(ctx context.Context, req *pb.GetCardsRequest, client GetCardsClient) (*pb.GetCardsResponse, error)
}

// DownstreamConfig for Cards
type DownstreamConfig struct {
	ContextTimeout time.Duration `yaml:"contextTimeout"`
}
