\appname
$'
ARG REGISTRY

FROM ${`${REGISTRY}${REGISTRY:+/}`}golang:alpine AS builder
WORKDIR /app
COPY . .
RUN go build -mod=vendor -o ${appname} ./cmd/${appname}

FROM ${`${REGISTRY}${REGISTRY:+/}`}alpine
WORKDIR /app
COPY --from=builder /app/${appname} /bin/
CMD ${appname}
' + '\n'
