let [_, spec, ...apps] = //os.args;
let apps = apps >> //seq.split(':', .);
$`
    SYSLGO_SYSL=${spec}
    SYSLGO_PACKAGES=${//seq.join(' ', apps >> .(1))}
    ${
        apps >> \[app, pkg] $`SYSLGO_APP.${pkg} = ${app}`
    ::\i:\n}
    -include local.mk
    include codegen.mk

`
