// Code generated by sysl DO NOT EDIT.
package downstream

import (
	"context"
	"time"
)

// DefaultDownstreamImpl ...
type DefaultDownstreamImpl struct {
}

// NewDefaultDownstreamImpl for Downstream
func NewDefaultDownstreamImpl() *DefaultDownstreamImpl {
	return &DefaultDownstreamImpl{}
}

// GetServiceDocsList Client
type GetServiceDocsListClient struct {
}

// ServiceInterface for Downstream
type ServiceInterface struct {
	GetServiceDocsList func(ctx context.Context, req *GetServiceDocsListRequest, client GetServiceDocsListClient) (*ServiceDoc, error)
}

// DownstreamConfig for Downstream
type DownstreamConfig struct {
	ContextTimeout time.Duration `yaml:"contextTimeout"`
}
