// Code generated by sysl DO NOT EDIT.
package downstream

import (
	"time"

	"github.com/anz-bank/sysl-go/validator"
	"github.com/rickb777/date"
)

// Reference imports to suppress unused errors
var _ = time.Parse

// Reference imports to suppress unused errors
var _ = date.Parse

// ServiceDoc ...
type ServiceDoc struct {
	Openapi string `json:"openapi"`
	Swagger string `json:"swagger"`
}

// Status ...
type Status struct {
	StatusField string `json:"statusField"`
}

// GetServiceDocsListRequest ...
type GetServiceDocsListRequest struct {
}

// *ServiceDoc validator
func (s *ServiceDoc) Validate() error {
	return validator.Validate(s)
}

// *Status validator
func (s *Status) Validate() error {
	return validator.Validate(s)
}
