// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_downstream.proto

package grpc_downstream

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetServiceDocRequest struct {
	Docid                string   `protobuf:"bytes,1,opt,name=docid,proto3" json:"docid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServiceDocRequest) Reset()         { *m = GetServiceDocRequest{} }
func (m *GetServiceDocRequest) String() string { return proto.CompactTextString(m) }
func (*GetServiceDocRequest) ProtoMessage()    {}
func (*GetServiceDocRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_96234c9042deeccc, []int{0}
}

func (m *GetServiceDocRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServiceDocRequest.Unmarshal(m, b)
}
func (m *GetServiceDocRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServiceDocRequest.Marshal(b, m, deterministic)
}
func (m *GetServiceDocRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServiceDocRequest.Merge(m, src)
}
func (m *GetServiceDocRequest) XXX_Size() int {
	return xxx_messageInfo_GetServiceDocRequest.Size(m)
}
func (m *GetServiceDocRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServiceDocRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetServiceDocRequest proto.InternalMessageInfo

func (m *GetServiceDocRequest) GetDocid() string {
	if m != nil {
		return m.Docid
	}
	return ""
}

type GetServiceDocResponse struct {
	ServiceDoc           *ServiceDoc `protobuf:"bytes,1,opt,name=serviceDoc,proto3" json:"serviceDoc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetServiceDocResponse) Reset()         { *m = GetServiceDocResponse{} }
func (m *GetServiceDocResponse) String() string { return proto.CompactTextString(m) }
func (*GetServiceDocResponse) ProtoMessage()    {}
func (*GetServiceDocResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_96234c9042deeccc, []int{1}
}

func (m *GetServiceDocResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServiceDocResponse.Unmarshal(m, b)
}
func (m *GetServiceDocResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServiceDocResponse.Marshal(b, m, deterministic)
}
func (m *GetServiceDocResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServiceDocResponse.Merge(m, src)
}
func (m *GetServiceDocResponse) XXX_Size() int {
	return xxx_messageInfo_GetServiceDocResponse.Size(m)
}
func (m *GetServiceDocResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServiceDocResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetServiceDocResponse proto.InternalMessageInfo

func (m *GetServiceDocResponse) GetServiceDoc() *ServiceDoc {
	if m != nil {
		return m.ServiceDoc
	}
	return nil
}

type ServiceDoc struct {
	Swagger              string   `protobuf:"bytes,1,opt,name=swagger,proto3" json:"swagger,omitempty"`
	Openapi              string   `protobuf:"bytes,2,opt,name=openapi,proto3" json:"openapi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceDoc) Reset()         { *m = ServiceDoc{} }
func (m *ServiceDoc) String() string { return proto.CompactTextString(m) }
func (*ServiceDoc) ProtoMessage()    {}
func (*ServiceDoc) Descriptor() ([]byte, []int) {
	return fileDescriptor_96234c9042deeccc, []int{2}
}

func (m *ServiceDoc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceDoc.Unmarshal(m, b)
}
func (m *ServiceDoc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceDoc.Marshal(b, m, deterministic)
}
func (m *ServiceDoc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceDoc.Merge(m, src)
}
func (m *ServiceDoc) XXX_Size() int {
	return xxx_messageInfo_ServiceDoc.Size(m)
}
func (m *ServiceDoc) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceDoc.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceDoc proto.InternalMessageInfo

func (m *ServiceDoc) GetSwagger() string {
	if m != nil {
		return m.Swagger
	}
	return ""
}

func (m *ServiceDoc) GetOpenapi() string {
	if m != nil {
		return m.Openapi
	}
	return ""
}

func init() {
	proto.RegisterType((*GetServiceDocRequest)(nil), "grpc_downstream.GetServiceDocRequest")
	proto.RegisterType((*GetServiceDocResponse)(nil), "grpc_downstream.GetServiceDocResponse")
	proto.RegisterType((*ServiceDoc)(nil), "grpc_downstream.ServiceDoc")
}

func init() { proto.RegisterFile("grpc_downstream.proto", fileDescriptor_96234c9042deeccc) }

var fileDescriptor_96234c9042deeccc = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0x2f, 0x2a, 0x48,
	0x8e, 0x4f, 0xc9, 0x2f, 0xcf, 0x2b, 0x2e, 0x29, 0x4a, 0x4d, 0xcc, 0xd5, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x47, 0x13, 0x56, 0xd2, 0xe1, 0x12, 0x71, 0x4f, 0x2d, 0x09, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x75, 0xc9, 0x4f, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe1,
	0x62, 0x4d, 0xc9, 0x4f, 0xce, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x94,
	0x42, 0xb8, 0x44, 0xd1, 0x54, 0x17, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x59, 0x73, 0x71, 0x15,
	0xc3, 0x45, 0xc1, 0x7a, 0xb8, 0x8d, 0xa4, 0xf5, 0xd0, 0xdd, 0x80, 0xa4, 0x11, 0x49, 0xb9, 0x92,
	0x03, 0x17, 0x17, 0x42, 0x46, 0x48, 0x82, 0x8b, 0xbd, 0xb8, 0x3c, 0x31, 0x3d, 0x3d, 0xb5, 0x08,
	0x6a, 0x37, 0x8c, 0x0b, 0x92, 0xc9, 0x2f, 0x48, 0xcd, 0x4b, 0x2c, 0xc8, 0x94, 0x60, 0x82, 0xc8,
	0x40, 0xb9, 0x46, 0x05, 0x5c, 0x7c, 0xee, 0x45, 0x05, 0xc9, 0x2e, 0x70, 0xab, 0x84, 0xe2, 0xb8,
	0x78, 0x51, 0x5c, 0x2a, 0xa4, 0x8a, 0xe1, 0x1a, 0x6c, 0xfe, 0x96, 0x52, 0x23, 0xa4, 0x0c, 0xe2,
	0xe1, 0x24, 0x36, 0x70, 0x78, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x75, 0xc1, 0x5e, 0xe1,
	0x68, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GrpcDownstreamClient is the client API for GrpcDownstream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcDownstreamClient interface {
	GetServiceDoc(ctx context.Context, in *GetServiceDocRequest, opts ...grpc.CallOption) (*GetServiceDocResponse, error)
}

type grpcDownstreamClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcDownstreamClient(cc grpc.ClientConnInterface) GrpcDownstreamClient {
	return &grpcDownstreamClient{cc}
}

func (c *grpcDownstreamClient) GetServiceDoc(ctx context.Context, in *GetServiceDocRequest, opts ...grpc.CallOption) (*GetServiceDocResponse, error) {
	out := new(GetServiceDocResponse)
	err := c.cc.Invoke(ctx, "/grpc_downstream.GrpcDownstream/GetServiceDoc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcDownstreamServer is the server API for GrpcDownstream service.
type GrpcDownstreamServer interface {
	GetServiceDoc(context.Context, *GetServiceDocRequest) (*GetServiceDocResponse, error)
}

// UnimplementedGrpcDownstreamServer can be embedded to have forward compatible implementations.
type UnimplementedGrpcDownstreamServer struct {
}

func (*UnimplementedGrpcDownstreamServer) GetServiceDoc(ctx context.Context, req *GetServiceDocRequest) (*GetServiceDocResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceDoc not implemented")
}

func RegisterGrpcDownstreamServer(s *grpc.Server, srv GrpcDownstreamServer) {
	s.RegisterService(&_GrpcDownstream_serviceDesc, srv)
}

func _GrpcDownstream_GetServiceDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceDocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcDownstreamServer).GetServiceDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_downstream.GrpcDownstream/GetServiceDoc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcDownstreamServer).GetServiceDoc(ctx, req.(*GetServiceDocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcDownstream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_downstream.GrpcDownstream",
	HandlerType: (*GrpcDownstreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceDoc",
			Handler:    _GrpcDownstream_GetServiceDoc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_downstream.proto",
}
