// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: wallet_api.proto

package cardspb

import (
	context "context"
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AppleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fpan string `protobuf:"bytes,1,opt,name=fpan,proto3" json:"fpan,omitempty"`
}

func (x *AppleRequest) Reset() {
	*x = AppleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wallet_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppleRequest) ProtoMessage() {}

func (x *AppleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppleRequest.ProtoReflect.Descriptor instead.
func (*AppleRequest) Descriptor() ([]byte, []int) {
	return file_wallet_api_proto_rawDescGZIP(), []int{0}
}

func (x *AppleRequest) GetFpan() string {
	if x != nil {
		return x.Fpan
	}
	return ""
}

type AppleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivationData string `protobuf:"bytes,1,opt,name=activation_data,json=activationData,proto3" json:"activation_data,omitempty"`
}

func (x *AppleResponse) Reset() {
	*x = AppleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wallet_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppleResponse) ProtoMessage() {}

func (x *AppleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppleResponse.ProtoReflect.Descriptor instead.
func (*AppleResponse) Descriptor() ([]byte, []int) {
	return file_wallet_api_proto_rawDescGZIP(), []int{1}
}

func (x *AppleResponse) GetActivationData() string {
	if x != nil {
		return x.ActivationData
	}
	return ""
}

var File_wallet_api_proto protoreflect.FileDescriptor

var file_wallet_api_proto_rawDesc = []byte{
	0x0a, 0x10, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x63, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x22, 0x0a, 0x0c,
	0x41, 0x70, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x66, 0x70, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x70, 0x61, 0x6e,
	0x22, 0x38, 0x0a, 0x0d, 0x41, 0x70, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x32, 0x42, 0x0a, 0x06, 0x57, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x12, 0x38, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x6c, 0x65, 0x12, 0x16, 0x2e,
	0x63, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x70, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09,
	0x5a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_wallet_api_proto_rawDescOnce sync.Once
	file_wallet_api_proto_rawDescData = file_wallet_api_proto_rawDesc
)

func file_wallet_api_proto_rawDescGZIP() []byte {
	file_wallet_api_proto_rawDescOnce.Do(func() {
		file_wallet_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_wallet_api_proto_rawDescData)
	})
	return file_wallet_api_proto_rawDescData
}

var file_wallet_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wallet_api_proto_goTypes = []interface{}{
	(*AppleRequest)(nil),  // 0: cards.v1.AppleRequest
	(*AppleResponse)(nil), // 1: cards.v1.AppleResponse
}
var file_wallet_api_proto_depIdxs = []int32{
	0, // 0: cards.v1.Wallet.Apple:input_type -> cards.v1.AppleRequest
	1, // 1: cards.v1.Wallet.Apple:output_type -> cards.v1.AppleResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wallet_api_proto_init() }
func file_wallet_api_proto_init() {
	if File_wallet_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wallet_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wallet_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wallet_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_api_proto_goTypes,
		DependencyIndexes: file_wallet_api_proto_depIdxs,
		MessageInfos:      file_wallet_api_proto_msgTypes,
	}.Build()
	File_wallet_api_proto = out.File
	file_wallet_api_proto_rawDesc = nil
	file_wallet_api_proto_goTypes = nil
	file_wallet_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WalletClient is the client API for Wallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletClient interface {
	Apple(ctx context.Context, in *AppleRequest, opts ...grpc.CallOption) (*AppleResponse, error)
}

type walletClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletClient(cc grpc.ClientConnInterface) WalletClient {
	return &walletClient{cc}
}

func (c *walletClient) Apple(ctx context.Context, in *AppleRequest, opts ...grpc.CallOption) (*AppleResponse, error) {
	out := new(AppleResponse)
	err := c.cc.Invoke(ctx, "/cards.v1.Wallet/Apple", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServer is the server API for Wallet service.
type WalletServer interface {
	Apple(context.Context, *AppleRequest) (*AppleResponse, error)
}

// UnimplementedWalletServer can be embedded to have forward compatible implementations.
type UnimplementedWalletServer struct {
}

func (*UnimplementedWalletServer) Apple(context.Context, *AppleRequest) (*AppleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Apple not implemented")
}

func RegisterWalletServer(s *grpc.Server, srv WalletServer) {
	s.RegisterService(&_Wallet_serviceDesc, srv)
}

func _Wallet_Apple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).Apple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cards.v1.Wallet/Apple",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).Apple(ctx, req.(*AppleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wallet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cards.v1.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apple",
			Handler:    _Wallet_Apple_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet_api.proto",
}
