// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet_api.proto

package cardspb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AppleRequest struct {
	Fpan                 string   `protobuf:"bytes,1,opt,name=fpan,proto3" json:"fpan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppleRequest) Reset()         { *m = AppleRequest{} }
func (m *AppleRequest) String() string { return proto.CompactTextString(m) }
func (*AppleRequest) ProtoMessage()    {}
func (*AppleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34bd94de71a6388e, []int{0}
}

func (m *AppleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppleRequest.Unmarshal(m, b)
}
func (m *AppleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppleRequest.Marshal(b, m, deterministic)
}
func (m *AppleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppleRequest.Merge(m, src)
}
func (m *AppleRequest) XXX_Size() int {
	return xxx_messageInfo_AppleRequest.Size(m)
}
func (m *AppleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppleRequest proto.InternalMessageInfo

func (m *AppleRequest) GetFpan() string {
	if m != nil {
		return m.Fpan
	}
	return ""
}

type AppleResponse struct {
	ActivationData       string   `protobuf:"bytes,1,opt,name=activation_data,json=activationData,proto3" json:"activation_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppleResponse) Reset()         { *m = AppleResponse{} }
func (m *AppleResponse) String() string { return proto.CompactTextString(m) }
func (*AppleResponse) ProtoMessage()    {}
func (*AppleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34bd94de71a6388e, []int{1}
}

func (m *AppleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppleResponse.Unmarshal(m, b)
}
func (m *AppleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppleResponse.Marshal(b, m, deterministic)
}
func (m *AppleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppleResponse.Merge(m, src)
}
func (m *AppleResponse) XXX_Size() int {
	return xxx_messageInfo_AppleResponse.Size(m)
}
func (m *AppleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppleResponse proto.InternalMessageInfo

func (m *AppleResponse) GetActivationData() string {
	if m != nil {
		return m.ActivationData
	}
	return ""
}

func init() {
	proto.RegisterType((*AppleRequest)(nil), "cards.v1.AppleRequest")
	proto.RegisterType((*AppleResponse)(nil), "cards.v1.AppleResponse")
}

func init() { proto.RegisterFile("wallet_api.proto", fileDescriptor_34bd94de71a6388e) }

var fileDescriptor_34bd94de71a6388e = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x4f, 0xcc, 0xc9,
	0x49, 0x2d, 0x89, 0x4f, 0x2c, 0xc8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0x4e,
	0x2c, 0x4a, 0x29, 0xd6, 0x2b, 0x33, 0x54, 0x52, 0xe2, 0xe2, 0x71, 0x2c, 0x28, 0xc8, 0x49, 0x0d,
	0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0x49, 0x2b, 0x48, 0xcc, 0x93, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x2c, 0xb8, 0x78, 0xa1, 0x6a, 0x8a, 0x0b, 0xf2,
	0xf3, 0x8a, 0x53, 0x85, 0xd4, 0xb9, 0xf8, 0x13, 0x93, 0x4b, 0x32, 0xcb, 0x12, 0x4b, 0x32, 0xf3,
	0xf3, 0xe2, 0x53, 0x12, 0x4b, 0x12, 0xa1, 0xea, 0xf9, 0x10, 0xc2, 0x2e, 0x89, 0x25, 0x89, 0x46,
	0x4e, 0x5c, 0x6c, 0xe1, 0x60, 0xbb, 0x85, 0x2c, 0xb8, 0x58, 0xc1, 0x66, 0x08, 0x89, 0xe9, 0xc1,
	0xec, 0xd6, 0x43, 0xb6, 0x58, 0x4a, 0x1c, 0x43, 0x1c, 0x62, 0x99, 0x13, 0x67, 0x14, 0x3b, 0x58,
	0xa6, 0x20, 0x29, 0x89, 0x0d, 0xec, 0x7a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x37, 0x17,
	0x46, 0x55, 0xd1, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WalletClient is the client API for Wallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletClient interface {
	Apple(ctx context.Context, in *AppleRequest, opts ...grpc.CallOption) (*AppleResponse, error)
}

type walletClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletClient(cc grpc.ClientConnInterface) WalletClient {
	return &walletClient{cc}
}

func (c *walletClient) Apple(ctx context.Context, in *AppleRequest, opts ...grpc.CallOption) (*AppleResponse, error) {
	out := new(AppleResponse)
	err := c.cc.Invoke(ctx, "/cards.v1.Wallet/Apple", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServer is the server API for Wallet service.
type WalletServer interface {
	Apple(context.Context, *AppleRequest) (*AppleResponse, error)
}

// UnimplementedWalletServer can be embedded to have forward compatible implementations.
type UnimplementedWalletServer struct {
}

func (*UnimplementedWalletServer) Apple(ctx context.Context, req *AppleRequest) (*AppleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Apple not implemented")
}

func RegisterWalletServer(s *grpc.Server, srv WalletServer) {
	s.RegisterService(&_Wallet_serviceDesc, srv)
}

func _Wallet_Apple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).Apple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cards.v1.Wallet/Apple",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).Apple(ctx, req.(*AppleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wallet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cards.v1.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apple",
			Handler:    _Wallet_Apple_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet_api.proto",
}
